theme: jekyll-theme-leap-day
show_downloads: "true"
title:  "Neural Network Basics"
description: [Jupyter notebooks that use TensorFlow to understand and visualize neural networks with applications in the Raspberry Pi]
